name: Build Xsmp Eclipse

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
    -  name: Setup Maven Action
       uses: s4u/setup-maven-action@v1.14.0
    # Maven build start
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Create P2 update repository
      run: |
        mvn clean package
        cp releng/repository/repo-index.html releng/repository/target/repository/index.html
    - name: Archive P2 Repository
      uses: actions/upload-artifact@v2
      with:
        name: p2-update-site
        path: |
          releng/repository/target/repository
        retention-days: 14
    - name: Purge Artifacts from Cache
      run: |
        mvn dependency:purge-local-repository -ntp
    # Maven build end

    - name: Publish to GH packages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: releng/repository/target/repository/
        destination_dir: download/updates/${{ github.ref_name }}

